# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_tokenizable}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Enrique Garcia Cota", "Francisco de Juan"]
  s.date = %q{2010-01-12}
  s.description = %q{Make ActiveRecord models easily searchable via tokens.}
  s.email = %q{github@splendeo.es}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "acts_as_tokenizable.gemspec",
     "init.rb",
     "lib/acts_as_tokenizable.rb",
     "lib/acts_as_tokenizable/acts_as_tokenizable.rb",
     "lib/acts_as_tokenizable/string_extensions.rb",
     "lib/tasks/tokenizer.rake",
     "test/helper.rb",
     "test/test_acts_as_tokenizable.rb"
  ]
  s.homepage = %q{http://github.com/splendeo/acts_as_tokenizable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Acts as tokenizable}
  s.test_files = [
    "test/helper.rb",
     "test/test_acts_as_tokenizable.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

